### ISSUE TITLE
Multiple 10x multiome reactions

### ISSUE THREAD

**Issue by alexwang1001** [chenweng1991/redeemV#2]
Dear Chen,

Thanks again for making this wonderful tool and pipeline available. I have run the redeemV pipeline smoothly and get all expected results. One issue I have, however, is that I have multiple 10x multiome reactions. Thus, after running the pipeline, have multiple QualifiedTotalCts and RawGenotypes files from each run. Correct me if I am wrong, but I don't think I can simply concatenate the files because of the potential shared barcodes from different cells from different 10x reactions. I wonder if you could provide some guidance on where and how to modify the redeemV output files from different reactions so that they can be combined/pooled for the downstream redeemR analysis.

Thank you,
Li

**Comment by chenweng1991** [comment]
Dear Li:
     I'm glad the pipeline runs smoothly.  Regarding the combing data, please check out this relevant issue link below. Basically, I would add suffix to different samples and then concatenate them for combined analysis.  It should work for most analysis. Please let me know if you have further questions regarding this.

The code provided below should be a good start, please feel free to modify on top of this.
https://github.com/chenweng1991/redeemR/issues/5

Thank you
Best regards
Chen

**Comment by alexwang1001** [comment]
That is very helpful. Thanks!
