### ISSUE TITLE
bsub command not found

### ISSUE THREAD

**Issue by petervangalen** [chenweng1991/redeemV#4]
In Step 5 of the [tutorial](https://github.com/chenweng1991/redeemV/blob/master/Tutorial_20221025.md), I got the error "bsub: command not found"
This is because the system I use has the Univa Grid Engine system. I fixed the issues as follows:

```
for ((i=1;i<=$Threads;i++))
  do qsub -N "Step5_$i" -o "Step5_$i.log" -l h_rt=4:00:00,h_vmem=16g -j y -b y -cwd python $mitoConsensus/mitoConsensus.py barcodes.$i $WD BC 30
done
```

Leaving this here in case it helps anyone else.

**Comment by chenweng1991** [comment]
Thank you for the helpful comments!
